### ISSUE TITLE
Add DB Index 

### ISSUE THREAD

**Issue by AndresFelipeRG** [corona-warn-app/cwa-server#275] opened 2020-05-23 18:30 UTC
## Current Implementation
Flyway PostGreSQL script

## Suggested Enhancement
Under the db/migration/postgres folder add a SQL script, using the CREATE INDEX command, to create a DB Index.

## Expected Benefits
Indexes are primarily used to enhance database performance

**Comment by jwedel** [comment] 2020-05-23 19:41
@AndresFelipeRG Is this a duplicate of #191?

**Closed** 2020-05-23 23:00 UTC
Labels: enhancement
