### ISSUE TITLE
Distribution: Align protocol to newest spec

### ISSUE THREAD

**Issue by christian-kirschnick** [corona-warn-app/cwa-server#79] opened 2020-05-12 12:40 UTC
Change our current proto spec to reflect the spec mentioned below. Create files based on this spec, instead of the old spec.

Currently, the spec is not available/final.

**Comment by pithumke** [comment] 2020-05-21 22:32
Linking #168 #200. Consider closing duplicates.

**Comment by michael-burwig** [comment] 2020-05-24 08:59
Duplicate of #168

**Closed by michael-burwig** 2020-05-24 08:59 UTC
Labels: DistributionSvc, further input needed
